version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/node-todo-cicd

hooks:
  ApplicationStop:
    - location: stop.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: start.sh
      timeout: 300
      runas: root
