version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/node-todo-cicd

# deploy on ec2 
hooks:
  BeforeInstall:
    - location: stop.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: start.sh
      timeout: 300
      runas: root    
